dist: trusty
sudo: false
language: node_js
node_js:
  - "8.9.3"
cache:
  directories:
    # Location of npm cache per https://docs.npmjs.com/cli/cache#cache. Shared by npx per
    # https://github.com/zkat/npx/tree/6e89dbd5989366e52d3810692b1ab5889a05fbad#description.
    - $HOME/.npm
install:
  - npx npm@$NPM_VERSION ci
